export const extendedTechSkills = [
  // Frontend Technologies
  "React",
  "Redux",
  "Vue.js",
  "Angular",
  "Svelte",
  "HTML",
  "CSS",
  "Sass",
  "Bootstrap",
  "Tailwind CSS",
  "jQuery",
  "WebAssembly",
  "Pug",
  "Grunt",
  "Gulp",
  "Webpack",
  "Parcel",
  "ES6",
  "TypeScript",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Storybook",
  "Semantic UI",
  "Material UI",
  "React Native",
  "Gatsby",
  "Next.js",
  "Ember.js",
  "Knockout.js",
  "Backbone.js",
  "Foundation",
  "Lit",
  "Prettier",
  "ESLint",

  // Backend Technologies
  "Node.js",
  "Express.js",
  "Koa.js",
  "NestJS",
  "Python",
  "Flask",
  "Django",
  "Ruby on Rails",
  "Java",
  "Spring Boot",
  "PHP",
  "Laravel",
  "C#",
  "ASP.NET",
  "Golang",
  "Rust",
  "Elixir",
  "Scala",
  "Swift",
  "Kotlin",
  "C++",
  "Objective-C",
  "R",
  "MATLAB",
  "Perl",
  "C",
  "F#",
  "GDScript",
  "Lua",
  "Dart",
  "Haskell",
  "Vala",
  "Crystal",

  // Cloud Computing
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Heroku",
  "IBM Cloud",
  "DigitalOcean",
  "CloudFormation",
  "Lambda",
  "EC2",
  "S3",
  "RDS",
  "Elastic Beanstalk",
  "EKS",
  "Fargate",
  "AWS Secrets Manager",
  "Cognito",
  "Route 53",
  "VPC",
  "CloudFront",
  "Azure Functions",
  "Google App Engine",
  "Firebase",
  "Cloud Run",
  "AWS Amplify",
  "Google Firebase",
  "Azure Kubernetes Service",
  "CloudFlare",
  "GCP BigQuery",
  "Google Cloud Storage",
  "AWS SQS",
  "DynamoDB",
  "Azure Blob Storage",

  // Databases
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "SQLite",
  "Firebase Realtime Database",
  "Google Firebase",
  "Cassandra",
  "MariaDB",
  "Oracle Database",
  "Amazon Aurora",
  "Google Cloud Firestore",
  "CouchDB",
  "Elasticsearch",
  "Neo4j",
  "GraphQL",
  "GraphQL Subscriptions",
  "DynamoDB",
  "Google BigQuery",
  "AWS Redshift",
  "CockroachDB",
  "IBM Db2",
  "MongoDB Atlas",
  "TimescaleDB",
  "Snowflake",

  // DevOps & CI/CD Tools
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "GitLab CI/CD",
  "GitHub Actions",
  "Bitbucket Pipelines",
  "ArgoCD",
  "Helm",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "Nagios",
  "Prometheus",
  "Grafana",
  "ElasticSearch",
  "Logstash",
  "Kibana",
  "Zabbix",
  "Sentry",
  "New Relic",
  "Datadog",
  "AWS ECS",
  "AWS EKS",
  "Docker Swarm",
  "Portainer",
  "Apache Kafka",
  "Consul",
  "Vault",
  "Packer",
  "Terraform Cloud",
  "Jfrog Artifactory",

  // Networking & Security
  "TCP/IP",
  "DNS",
  "HTTP",
  "HTTPS",
  "SSL/TLS",
  "SSH",
  "VPN",
  "Load Balancer",
  "Firewall",
  "Proxies",
  "Network Security",
  "DDOS Protection",
  "PKI",
  "IPSec",
  "NAT",
  "Routing",
  "Switching",
  "MPLS",
  "OSI Model",
  "Wireshark",
  "Nmap",
  "Port Scanning",
  "Network Monitoring",
  "Snort",
  "Suricata",
  "Honeypot",
  "OpenVPN",
  "WireGuard",
  "BGP",
  "DHCP",
  "IPv4",
  "IPv6",
  "WiFi Security",
  "Network Topology",
  "SDN",
  "5G",
  "Wi-Fi 6",

  // Mobile Development
  "React Native",
  "Flutter",
  "Xamarin",
  "Swift",
  "Objective-C",
  "Kotlin",
  "Java",
  "Cocoa Touch",
  "Android SDK",
  "iOS SDK",
  "Gradle",
  "Fastlane",
  "Appium",
  "TestFlight",
  "Firebase Cloud Messaging",
  "Realm",
  "Core Data",
  "RxJava",
  "Android Jetpack",
  "Android Architecture Components",
  "Push Notifications",
  "Objective-C Runtime",
  "J2EE",
  "Coroutines",
  "Jetpack Compose",
  "Google Play Console",
  "App Store Connect",

  // Machine Learning & AI
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "OpenCV",
  "FastAI",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Seaborn",
  "XGBoost",
  "LightGBM",
  "CatBoost",
  "GPT-3",
  "BERT",
  "Transformer Models",
  "Reinforcement Learning",
  "Neural Networks",
  "NLP",
  "Computer Vision",
  "Natural Language Processing",
  "Image Recognition",
  "Speech Recognition",
  "Generative Adversarial Networks (GANs)",
  "Deep Learning",
  "AI Ethics",
  "AI Bias",
  "AI Algorithms",
  "Predictive Analytics",

  // Data Science & Analytics
  "Data Analysis",
  "Data Visualization",
  "Big Data",
  "Apache Spark",
  "Hadoop",
  "Apache Kafka",
  "SQL",
  "NoSQL",
  "Data Cleansing",
  "Data Mining",
  "Exploratory Data Analysis",
  "Feature Engineering",
  "Dimensionality Reduction",
  "Clustering",
  "Classification",
  "Regressions",
  "A/B Testing",
  "Business Intelligence",
  "Tableau",
  "Power BI",
  "QlikView",
  "Excel",
  "Google Analytics",
  "Data Warehousing",
  "ETL Pipelines",
  "Jupyter Notebooks",
  "R Studio",
  "SAS",

  // UI/UX Design
  "Figma",
  "Sketch",
  "Adobe XD",
  "Wireframing",
  "Prototyping",
  "User Testing",
  "Interaction Design",
  "User Experience",
  "User Interface Design",
  "UI Prototyping",
  "Usability Testing",
  "Persona Development",
  "Storyboarding",
  "Responsive Design",
  "CSS Animations",
  "Material Design",
  "Design Systems",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "InVision",
  "Zeplin",
  "Mockups",
  "User Flows",

  // Agile & Project Management
  "Scrum",
  "Kanban",
  "JIRA",
  "Trello",
  "Asana",
  "Confluence",
  "Agile Methodology",
  "Waterfall",
  "Lean",
  "DevOps",
  "Project Management",
  "Product Management",
  "Team Collaboration",
  "User Stories",
  "Sprints",
  "Backlog Grooming",
  "Burndown Charts",
  "Stakeholder Management",
  "Risk Management",

  // Version Control Systems
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "SVN",
  "Mercurial",
  "Perforce",
  "Git Hooks",
  "Git Flow",
  "Git Submodules",

  // Other Tools and Libraries
  "GraphQL",
  "WebSockets",
  "Socket.io",
  "RESTful APIs",
  "JSON",
  "XML",
  "SOAP",
  "OAuth2",
  "JWT",
  "Swagger",
  "Postman",
  "JUnit",
  "Mockito",
  "Selenium",
  "Cypress",
  "Appium",
  "JUnit5",
  "TestNG",
  "JUnit Assertions",
  "TDD",
  "BDD",
  "Gherkin",
  "Cucumber",
  "Jest",
  "Mocha",
  "Chai",
  "Puppeteer",
  "Apache HTTP Server",
  "Nginx",
  "NGINX Ingress Controller",
  "Apache Kafka",
  "Redis",
  "RabbitMQ",
  "ZeroMQ",
  "MQTT",
  "Capistrano",
  "Capistrano Deploy",
  "Selenium Grid",
  "Vagrant",
  "VirtualBox",
  "Docker Compose",
  "Docker Registry",
  "Minikube",
  "Vagrant",

  // Emerging Technologies
  "Quantum Computing",
  "Blockchain",
  "Cryptocurrency",
  "Smart Contracts",
  "Ethereum",
  "Solidity",
  "Web3.js",
  "IPFS",
  "Decentralized Applications (DApps)",
  "NFTs",
  "Decentralized Finance (DeFi)",
  "Hyperledger",
  "IBM Blockchain",
  "Cryptography",
  "Security Tokens",
  "Tokenomics",
  "ICO",
  "DAO",
];
