services:
  mongo1:
    image: mongo:7.0
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo_network

  mongo2:
    image: mongo:7.0
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo_network

  mongo3:
    image: mongo:7.0
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27020:27017"
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
